/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ForecastTemperature', function() {
      beforeEach(function() {
        instance = new HomeIotApi.ForecastTemperature();
      });

      it('should create an instance of ForecastTemperature', function() {
        // TODO: update the code to test ForecastTemperature
        expect(instance).to.be.a(HomeIotApi.ForecastTemperature);
      });

      it('should have the property low (base name: "low")', function() {
        // TODO: update the code to test the property low
        expect(instance).to.have.property('low');
        // expect(instance.low).to.be(expectedValueLiteral);
      });

      it('should have the property high (base name: "high")', function() {
        // TODO: update the code to test the property high
        expect(instance).to.have.property('high');
        // expect(instance.high).to.be(expectedValueLiteral);
      });

      it('should have the property morning (base name: "morning")', function() {
        // TODO: update the code to test the property morning
        expect(instance).to.have.property('morning');
        // expect(instance.morning).to.be(expectedValueLiteral);
      });

      it('should have the property day (base name: "day")', function() {
        // TODO: update the code to test the property day
        expect(instance).to.have.property('day');
        // expect(instance.day).to.be(expectedValueLiteral);
      });

      it('should have the property evening (base name: "evening")', function() {
        // TODO: update the code to test the property evening
        expect(instance).to.have.property('evening');
        // expect(instance.evening).to.be(expectedValueLiteral);
      });

      it('should have the property night (base name: "night")', function() {
        // TODO: update the code to test the property night
        expect(instance).to.have.property('night');
        // expect(instance.night).to.be(expectedValueLiteral);
      });

    });
  });

}));
