/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Forecast', function() {
      beforeEach(function() {
        instance = new HomeIotApi.Forecast();
      });

      it('should create an instance of Forecast', function() {
        // TODO: update the code to test Forecast
        expect(instance).to.be.a(HomeIotApi.Forecast);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property pressure (base name: "pressure")', function() {
        // TODO: update the code to test the property pressure
        expect(instance).to.have.property('pressure');
        // expect(instance.pressure).to.be(expectedValueLiteral);
      });

      it('should have the property humidity (base name: "humidity")', function() {
        // TODO: update the code to test the property humidity
        expect(instance).to.have.property('humidity');
        // expect(instance.humidity).to.be(expectedValueLiteral);
      });

      it('should have the property windSpeed (base name: "windSpeed")', function() {
        // TODO: update the code to test the property windSpeed
        expect(instance).to.have.property('windSpeed');
        // expect(instance.windSpeed).to.be(expectedValueLiteral);
      });

      it('should have the property clouds (base name: "clouds")', function() {
        // TODO: update the code to test the property clouds
        expect(instance).to.have.property('clouds');
        // expect(instance.clouds).to.be(expectedValueLiteral);
      });

      it('should have the property temperature (base name: "temperature")', function() {
        // TODO: update the code to test the property temperature
        expect(instance).to.have.property('temperature');
        // expect(instance.temperature).to.be(expectedValueLiteral);
      });

      it('should have the property weather (base name: "weather")', function() {
        // TODO: update the code to test the property weather
        expect(instance).to.have.property('weather');
        // expect(instance.weather).to.be(expectedValueLiteral);
      });

    });
  });

}));
