/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LightingSummary', function() {
      beforeEach(function() {
        instance = new HomeIotApi.LightingSummary();
      });

      it('should create an instance of LightingSummary', function() {
        // TODO: update the code to test LightingSummary
        expect(instance).to.be.a(HomeIotApi.LightingSummary);
      });

      it('should have the property zones (base name: "zones")', function() {
        // TODO: update the code to test the property zones
        expect(instance).to.have.property('zones');
        // expect(instance.zones).to.be(expectedValueLiteral);
      });

      it('should have the property zoneStatus (base name: "zoneStatus")', function() {
        // TODO: update the code to test the property zoneStatus
        expect(instance).to.have.property('zoneStatus');
        // expect(instance.zoneStatus).to.be(expectedValueLiteral);
      });

    });
  });

}));
