/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WeatherForecast', function() {
      beforeEach(function() {
        instance = new HomeIotApi.WeatherForecast();
      });

      it('should create an instance of WeatherForecast', function() {
        // TODO: update the code to test WeatherForecast
        expect(instance).to.be.a(HomeIotApi.WeatherForecast);
      });

      it('should have the property summary (base name: "summary")', function() {
        // TODO: update the code to test the property summary
        expect(instance).to.have.property('summary');
        // expect(instance.summary).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property icon (base name: "icon")', function() {
        // TODO: update the code to test the property icon
        expect(instance).to.have.property('icon');
        // expect(instance.icon).to.be(expectedValueLiteral);
      });

    });
  });

}));
