/*
 * Calculator API
 * An API for performing basic arithmetic calculations
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {InlineResponse200} from '../model/InlineResponse200';
import {InlineResponse2001} from '../model/InlineResponse2001';
import {InlineResponse2002} from '../model/InlineResponse2002';
import {InlineResponse2003} from '../model/InlineResponse2003';
import {InlineResponse2004} from '../model/InlineResponse2004';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addABGet operation.
     * @callback moduleapi/DefaultApi~addABGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform addition operation
     * Adds two numbers and returns the result.
     * @param {Number} a The first number to be added.
     * @param {Number} b The second number to be added.
     * @param {module:api/DefaultApi~addABGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addABGet(a, b, callback) {
      
      let postBody = null;
      // verify the required parameter 'a' is set
      if (a === undefined || a === null) {
        throw new Error("Missing the required parameter 'a' when calling addABGet");
      }
      // verify the required parameter 'b' is set
      if (b === undefined || b === null) {
        throw new Error("Missing the required parameter 'b' when calling addABGet");
      }

      let pathParams = {
        'a': a,'b': b
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/add/{a}/{b}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the divideABGet operation.
     * @callback moduleapi/DefaultApi~divideABGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform division operation
     * Divides the first number by the second number and returns the result.
     * @param {Number} a The number to be divided.
     * @param {Number} b The number to divide by.
     * @param {module:api/DefaultApi~divideABGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    divideABGet(a, b, callback) {
      
      let postBody = null;
      // verify the required parameter 'a' is set
      if (a === undefined || a === null) {
        throw new Error("Missing the required parameter 'a' when calling divideABGet");
      }
      // verify the required parameter 'b' is set
      if (b === undefined || b === null) {
        throw new Error("Missing the required parameter 'b' when calling divideABGet");
      }

      let pathParams = {
        'a': a,'b': b
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/divide/{a}/{b}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the multiplyABGet operation.
     * @callback moduleapi/DefaultApi~multiplyABGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform multiplication operation
     * Multiplies two numbers and returns the result.
     * @param {Number} a The first number to be multiplied.
     * @param {Number} b The second number to be multiplied.
     * @param {module:api/DefaultApi~multiplyABGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    multiplyABGet(a, b, callback) {
      
      let postBody = null;
      // verify the required parameter 'a' is set
      if (a === undefined || a === null) {
        throw new Error("Missing the required parameter 'a' when calling multiplyABGet");
      }
      // verify the required parameter 'b' is set
      if (b === undefined || b === null) {
        throw new Error("Missing the required parameter 'b' when calling multiplyABGet");
      }

      let pathParams = {
        'a': a,'b': b
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/multiply/{a}/{b}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the rootGet operation.
     * @callback moduleapi/DefaultApi~rootGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get available routes
     * Returns the available routes and their descriptions.
     * @param {module:api/DefaultApi~rootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    rootGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the subtractABGet operation.
     * @callback moduleapi/DefaultApi~subtractABGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform subtraction operation
     * Subtracts the second number from the first number and returns the result.
     * @param {Number} a The number to be subtracted from.
     * @param {Number} b The number to subtract.
     * @param {module:api/DefaultApi~subtractABGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    subtractABGet(a, b, callback) {
      
      let postBody = null;
      // verify the required parameter 'a' is set
      if (a === undefined || a === null) {
        throw new Error("Missing the required parameter 'a' when calling subtractABGet");
      }
      // verify the required parameter 'b' is set
      if (b === undefined || b === null) {
        throw new Error("Missing the required parameter 'b' when calling subtractABGet");
      }

      let pathParams = {
        'a': a,'b': b
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/subtract/{a}/{b}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}