/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ApiResponse} from './model/ApiResponse';
import {City} from './model/City';
import {DeviceRegistrationInfo} from './model/DeviceRegistrationInfo';
import {DeviceState} from './model/DeviceState';
import {Forecast} from './model/Forecast';
import {ForecastResponse} from './model/ForecastResponse';
import {ForecastTemperature} from './model/ForecastTemperature';
import {HeaterState} from './model/HeaterState';
import {LightingSummary} from './model/LightingSummary';
import {LightingZone} from './model/LightingZone';
import {LightingZoneStatus} from './model/LightingZoneStatus';
import {TemperatueZoneStatus} from './model/TemperatueZoneStatus';
import {TemperatureSummary} from './model/TemperatureSummary';
import {TemperatureZone} from './model/TemperatureZone';
import {WeatherForecast} from './model/WeatherForecast';
import {DeviceApi} from './api/DeviceApi';
import {EnvironmentApi} from './api/EnvironmentApi';
import {ZWaveApi} from './api/ZWaveApi';
import {ZonesApi} from './api/ZonesApi';

/**
* The_API_for_the_EatBacon_IOT_project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HomeIotApi = require('index'); // See note below*.
* var xxxSvc = new HomeIotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HomeIotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HomeIotApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HomeIotApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse,

    /**
     * The City model constructor.
     * @property {module:model/City}
     */
    City,

    /**
     * The DeviceRegistrationInfo model constructor.
     * @property {module:model/DeviceRegistrationInfo}
     */
    DeviceRegistrationInfo,

    /**
     * The DeviceState model constructor.
     * @property {module:model/DeviceState}
     */
    DeviceState,

    /**
     * The Forecast model constructor.
     * @property {module:model/Forecast}
     */
    Forecast,

    /**
     * The ForecastResponse model constructor.
     * @property {module:model/ForecastResponse}
     */
    ForecastResponse,

    /**
     * The ForecastTemperature model constructor.
     * @property {module:model/ForecastTemperature}
     */
    ForecastTemperature,

    /**
     * The HeaterState model constructor.
     * @property {module:model/HeaterState}
     */
    HeaterState,

    /**
     * The LightingSummary model constructor.
     * @property {module:model/LightingSummary}
     */
    LightingSummary,

    /**
     * The LightingZone model constructor.
     * @property {module:model/LightingZone}
     */
    LightingZone,

    /**
     * The LightingZoneStatus model constructor.
     * @property {module:model/LightingZoneStatus}
     */
    LightingZoneStatus,

    /**
     * The TemperatueZoneStatus model constructor.
     * @property {module:model/TemperatueZoneStatus}
     */
    TemperatueZoneStatus,

    /**
     * The TemperatureSummary model constructor.
     * @property {module:model/TemperatureSummary}
     */
    TemperatureSummary,

    /**
     * The TemperatureZone model constructor.
     * @property {module:model/TemperatureZone}
     */
    TemperatureZone,

    /**
     * The WeatherForecast model constructor.
     * @property {module:model/WeatherForecast}
     */
    WeatherForecast,

    /**
    * The DeviceApi service constructor.
    * @property {module:api/DeviceApi}
    */
    DeviceApi,

    /**
    * The EnvironmentApi service constructor.
    * @property {module:api/EnvironmentApi}
    */
    EnvironmentApi,

    /**
    * The ZWaveApi service constructor.
    * @property {module:api/ZWaveApi}
    */
    ZWaveApi,

    /**
    * The ZonesApi service constructor.
    * @property {module:api/ZonesApi}
    */
    ZonesApi
};
