/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The City model module.
 * @module model/City
 * @version 1.0.0
 */
export class City {
  /**
   * Constructs a new <code>City</code>.
   * @alias module:model/City
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>City</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/City} obj Optional instance to populate.
   * @return {module:model/City} The populated <code>City</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new City();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('lat'))
        obj.lat = ApiClient.convertToType(data['lat'], 'Number');
      if (data.hasOwnProperty('lon'))
        obj.lon = ApiClient.convertToType(data['lon'], 'Number');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
City.prototype.id = undefined;

/**
 * @member {String} name
 */
City.prototype.name = undefined;

/**
 * @member {Number} lat
 */
City.prototype.lat = undefined;

/**
 * @member {Number} lon
 */
City.prototype.lon = undefined;

/**
 * @member {String} country
 */
City.prototype.country = undefined;

