/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeviceState model module.
 * @module model/DeviceState
 * @version 1.0.0
 */
export class DeviceState {
  /**
   * Constructs a new <code>DeviceState</code>.
   * @alias module:model/DeviceState
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeviceState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceState} obj Optional instance to populate.
   * @return {module:model/DeviceState} The populated <code>DeviceState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceState();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('lastUpdate'))
        obj.lastUpdate = ApiClient.convertToType(data['lastUpdate'], 'Date');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
DeviceState.prototype.id = undefined;

/**
 * @member {String} name
 */
DeviceState.prototype.name = undefined;

/**
 * @member {Date} lastUpdate
 */
DeviceState.prototype.lastUpdate = undefined;

/**
 * @member {Number} level
 */
DeviceState.prototype.level = undefined;

