/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeviceRegistrationInfo model module.
 * @module model/DeviceRegistrationInfo
 * @version 1.0.0
 */
export class DeviceRegistrationInfo {
  /**
   * Constructs a new <code>DeviceRegistrationInfo</code>.
   * @alias module:model/DeviceRegistrationInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeviceRegistrationInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceRegistrationInfo} obj Optional instance to populate.
   * @return {module:model/DeviceRegistrationInfo} The populated <code>DeviceRegistrationInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceRegistrationInfo();
      if (data.hasOwnProperty('uri'))
        obj.uri = ApiClient.convertToType(data['uri'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} uri
 */
DeviceRegistrationInfo.prototype.uri = undefined;

/**
 * @member {String} id
 */
DeviceRegistrationInfo.prototype.id = undefined;

