/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {City} from './City';
import {Forecast} from './Forecast';

/**
 * The ForecastResponse model module.
 * @module model/ForecastResponse
 * @version 1.0.0
 */
export class ForecastResponse {
  /**
   * Constructs a new <code>ForecastResponse</code>.
   * @alias module:model/ForecastResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ForecastResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForecastResponse} obj Optional instance to populate.
   * @return {module:model/ForecastResponse} The populated <code>ForecastResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ForecastResponse();
      if (data.hasOwnProperty('city'))
        obj.city = City.constructFromObject(data['city']);
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], [Forecast]);
    }
    return obj;
  }
}

/**
 * @member {module:model/City} city
 */
ForecastResponse.prototype.city = undefined;

/**
 * @member {Array.<module:model/Forecast>} values
 */
ForecastResponse.prototype.values = undefined;

