/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ForecastTemperature model module.
 * @module model/ForecastTemperature
 * @version 1.0.0
 */
export class ForecastTemperature {
  /**
   * Constructs a new <code>ForecastTemperature</code>.
   * @alias module:model/ForecastTemperature
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ForecastTemperature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ForecastTemperature} obj Optional instance to populate.
   * @return {module:model/ForecastTemperature} The populated <code>ForecastTemperature</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ForecastTemperature();
      if (data.hasOwnProperty('low'))
        obj.low = ApiClient.convertToType(data['low'], 'Number');
      if (data.hasOwnProperty('high'))
        obj.high = ApiClient.convertToType(data['high'], 'Number');
      if (data.hasOwnProperty('morning'))
        obj.morning = ApiClient.convertToType(data['morning'], 'Number');
      if (data.hasOwnProperty('day'))
        obj.day = ApiClient.convertToType(data['day'], 'Number');
      if (data.hasOwnProperty('evening'))
        obj.evening = ApiClient.convertToType(data['evening'], 'Number');
      if (data.hasOwnProperty('night'))
        obj.night = ApiClient.convertToType(data['night'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} low
 */
ForecastTemperature.prototype.low = undefined;

/**
 * @member {Number} high
 */
ForecastTemperature.prototype.high = undefined;

/**
 * @member {Number} morning
 */
ForecastTemperature.prototype.morning = undefined;

/**
 * @member {Number} day
 */
ForecastTemperature.prototype.day = undefined;

/**
 * @member {Number} evening
 */
ForecastTemperature.prototype.evening = undefined;

/**
 * @member {Number} night
 */
ForecastTemperature.prototype.night = undefined;

