/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HeaterState model module.
 * @module model/HeaterState
 * @version 1.0.0
 */
export class HeaterState {
  /**
   * Constructs a new <code>HeaterState</code>.
   * @alias module:model/HeaterState
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HeaterState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HeaterState} obj Optional instance to populate.
   * @return {module:model/HeaterState} The populated <code>HeaterState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HeaterState();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
HeaterState.prototype.id = undefined;

/**
 * @member {String} state
 */
HeaterState.prototype.state = undefined;

