/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {LightingZone} from './LightingZone';
import {LightingZoneStatus} from './LightingZoneStatus';

/**
 * The LightingSummary model module.
 * @module model/LightingSummary
 * @version 1.0.0
 */
export class LightingSummary {
  /**
   * Constructs a new <code>LightingSummary</code>.
   * ok
   * @alias module:model/LightingSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LightingSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LightingSummary} obj Optional instance to populate.
   * @return {module:model/LightingSummary} The populated <code>LightingSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LightingSummary();
      if (data.hasOwnProperty('zones'))
        obj.zones = ApiClient.convertToType(data['zones'], [LightingZone]);
      if (data.hasOwnProperty('zoneStatus'))
        obj.zoneStatus = ApiClient.convertToType(data['zoneStatus'], [LightingZoneStatus]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/LightingZone>} zones
 */
LightingSummary.prototype.zones = undefined;

/**
 * @member {Array.<module:model/LightingZoneStatus>} zoneStatus
 */
LightingSummary.prototype.zoneStatus = undefined;

