/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LightingZone model module.
 * @module model/LightingZone
 * @version 1.0.0
 */
export class LightingZone {
  /**
   * Constructs a new <code>LightingZone</code>.
   * @alias module:model/LightingZone
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LightingZone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LightingZone} obj Optional instance to populate.
   * @return {module:model/LightingZone} The populated <code>LightingZone</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LightingZone();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('deviceId'))
        obj.deviceId = ApiClient.convertToType(data['deviceId'], 'Number');
      if (data.hasOwnProperty('deviceType'))
        obj.deviceType = ApiClient.convertToType(data['deviceType'], 'String');
      if (data.hasOwnProperty('zone'))
        obj.zone = ApiClient.convertToType(data['zone'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
LightingZone.prototype.id = undefined;

/**
 * @member {String} name
 */
LightingZone.prototype.name = undefined;

/**
 * @member {Number} deviceId
 */
LightingZone.prototype.deviceId = undefined;

/**
 * Allowed values for the <code>deviceType</code> property.
 * @enum {String}
 * @readonly
 */
LightingZone.DeviceTypeEnum = {
  /**
   * value: "dimmer"
   * @const
   */
  dimmer: "dimmer",

  /**
   * value: "switch"
   * @const
   */
  _switch: "switch"
};
/**
 * @member {module:model/LightingZone.DeviceTypeEnum} deviceType
 */
LightingZone.prototype.deviceType = undefined;

/**
 * @member {String} zone
 */
LightingZone.prototype.zone = undefined;

