/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TemperatureZone model module.
 * @module model/TemperatureZone
 * @version 1.0.0
 */
export class TemperatureZone {
  /**
   * Constructs a new <code>TemperatureZone</code>.
   * a single temperature zone
   * @alias module:model/TemperatureZone
   * @class
   * @param id {Number} the unique identifier for the zone
   * @param name {String} 
   */
  constructor(id, name) {
    this.id = id;
    this.name = name;
  }

  /**
   * Constructs a <code>TemperatureZone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemperatureZone} obj Optional instance to populate.
   * @return {module:model/TemperatureZone} The populated <code>TemperatureZone</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TemperatureZone();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('inputPosition'))
        obj.inputPosition = ApiClient.convertToType(data['inputPosition'], 'Number');
      if (data.hasOwnProperty('outputPosition'))
        obj.outputPosition = ApiClient.convertToType(data['outputPosition'], 'Number');
      if (data.hasOwnProperty('zone'))
        obj.zone = ApiClient.convertToType(data['zone'], 'String');
    }
    return obj;
  }
}

/**
 * the unique identifier for the zone
 * @member {Number} id
 */
TemperatureZone.prototype.id = undefined;

/**
 * @member {String} name
 */
TemperatureZone.prototype.name = undefined;

/**
 * @member {Number} inputPosition
 */
TemperatureZone.prototype.inputPosition = undefined;

/**
 * @member {Number} outputPosition
 */
TemperatureZone.prototype.outputPosition = undefined;

/**
 * @member {String} zone
 */
TemperatureZone.prototype.zone = undefined;

