/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TemperatueZoneStatus} from './TemperatueZoneStatus';
import {TemperatureZone} from './TemperatureZone';

/**
 * The TemperatureSummary model module.
 * @module model/TemperatureSummary
 * @version 1.0.0
 */
export class TemperatureSummary {
  /**
   * Constructs a new <code>TemperatureSummary</code>.
   * ok
   * @alias module:model/TemperatureSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TemperatureSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemperatureSummary} obj Optional instance to populate.
   * @return {module:model/TemperatureSummary} The populated <code>TemperatureSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TemperatureSummary();
      if (data.hasOwnProperty('zones'))
        obj.zones = ApiClient.convertToType(data['zones'], [TemperatureZone]);
      if (data.hasOwnProperty('zoneStatus'))
        obj.zoneStatus = ApiClient.convertToType(data['zoneStatus'], [TemperatueZoneStatus]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/TemperatureZone>} zones
 */
TemperatureSummary.prototype.zones = undefined;

/**
 * @member {Array.<module:model/TemperatueZoneStatus>} zoneStatus
 */
TemperatureSummary.prototype.zoneStatus = undefined;

