/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WeatherForecast model module.
 * @module model/WeatherForecast
 * @version 1.0.0
 */
export class WeatherForecast {
  /**
   * Constructs a new <code>WeatherForecast</code>.
   * @alias module:model/WeatherForecast
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WeatherForecast</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WeatherForecast} obj Optional instance to populate.
   * @return {module:model/WeatherForecast} The populated <code>WeatherForecast</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WeatherForecast();
      if (data.hasOwnProperty('summary'))
        obj.summary = ApiClient.convertToType(data['summary'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('icon'))
        obj.icon = ApiClient.convertToType(data['icon'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} summary
 */
WeatherForecast.prototype.summary = undefined;

/**
 * @member {String} description
 */
WeatherForecast.prototype.description = undefined;

/**
 * @member {String} icon
 */
WeatherForecast.prototype.icon = undefined;

