/*
 * Calculator API
 * An API for performing basic arithmetic calculations.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CalculatorApi);
  }
}(this, function(expect, CalculatorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CalculatorApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('addABGet', function() {
        it('should call addABGet successfully', function(done) {
          // TODO: uncomment, update parameter values for addABGet call and complete the assertions
          /*

          instance.addABGet(a, b, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CalculatorApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('divideABGet', function() {
        it('should call divideABGet successfully', function(done) {
          // TODO: uncomment, update parameter values for divideABGet call and complete the assertions
          /*

          instance.divideABGet(a, b, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CalculatorApi.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('multiplyABGet', function() {
        it('should call multiplyABGet successfully', function(done) {
          // TODO: uncomment, update parameter values for multiplyABGet call and complete the assertions
          /*

          instance.multiplyABGet(a, b, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CalculatorApi.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('rootGet', function() {
        it('should call rootGet successfully', function(done) {
          // TODO: uncomment rootGet call and complete the assertions
          /*

          instance.rootGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CalculatorApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('subtractABGet', function() {
        it('should call subtractABGet successfully', function(done) {
          // TODO: uncomment, update parameter values for subtractABGet call and complete the assertions
          /*

          instance.subtractABGet(a, b, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CalculatorApi.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
