/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HomeIotApi.EnvironmentApi();
  });

  describe('(package)', function() {
    describe('EnvironmentApi', function() {
      describe('getForecast', function() {
        it('should call getForecast successfully', function(done) {
          // TODO: uncomment, update parameter values for getForecast call and complete the assertions
          /*

          instance.getForecast(days, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ForecastResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getHeaterState', function() {
        it('should call getHeaterState successfully', function(done) {
          // TODO: uncomment, update parameter values for getHeaterState call and complete the assertions
          /*

          instance.getHeaterState(zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.HeaterState);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getZoneTemperature', function() {
        it('should call getZoneTemperature successfully', function(done) {
          // TODO: uncomment, update parameter values for getZoneTemperature call and complete the assertions
          /*

          instance.getZoneTemperature(zoneId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.TemperatueZoneStatus);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setHeaterState', function() {
        it('should call setHeaterState successfully', function(done) {
          // TODO: uncomment, update parameter values for setHeaterState call and complete the assertions
          /*

          instance.setHeaterState(zoneId, state, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ApiResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('temperatureSummary', function() {
        it('should call temperatureSummary successfully', function(done) {
          // TODO: uncomment temperatureSummary call and complete the assertions
          /*

          instance.temperatureSummary(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.TemperatureSummary);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
