/*
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HomeIotApi);
  }
}(this, function(expect, HomeIotApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HomeIotApi.ZWaveApi();
  });

  describe('(package)', function() {
    describe('ZWaveApi', function() {
      describe('getLightingSummary', function() {
        it('should call getLightingSummary successfully', function(done) {
          // TODO: uncomment getLightingSummary call and complete the assertions
          /*

          instance.getLightingSummary(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.LightingSummary);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSwitchState', function() {
        it('should call getSwitchState successfully', function(done) {
          // TODO: uncomment, update parameter values for getSwitchState call and complete the assertions
          /*

          instance.getSwitchState(deviceId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.DeviceState);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setDimmer', function() {
        it('should call setDimmer successfully', function(done) {
          // TODO: uncomment, update parameter values for setDimmer call and complete the assertions
          /*

          instance.setDimmer(deviceId, value, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ApiResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setDimmerTimer', function() {
        it('should call setDimmerTimer successfully', function(done) {
          // TODO: uncomment, update parameter values for setDimmerTimer call and complete the assertions
          /*
          var opts = {};

          instance.setDimmerTimer(deviceId, value, timeunit, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ApiResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setSwitch', function() {
        it('should call setSwitch successfully', function(done) {
          // TODO: uncomment, update parameter values for setSwitch call and complete the assertions
          /*

          instance.setSwitch(deviceId, value, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ApiResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setSwitchTimer', function() {
        it('should call setSwitchTimer successfully', function(done) {
          // TODO: uncomment, update parameter values for setSwitchTimer call and complete the assertions
          /*

          instance.setSwitchTimer(deviceId, value, minutes, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HomeIotApi.ApiResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
